<?php

namespace ContainerXVoTJ3Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BXCrr1rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BXCrr1r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BXCrr1r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator._1ARgjp.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\Admin\\TaskCrudController::configureActions' => ['privates', '.service_locator.LHPXyzR.App\\Controller\\Admin\\TaskCrudController::configureActions()', 'getTaskCrudControllerconfigureActionsService', true],
            'App\\Controller\\Admin\\TaskCrudController::configureCrud' => ['privates', '.service_locator.GLGWHcU.App\\Controller\\Admin\\TaskCrudController::configureCrud()', 'getTaskCrudControllerconfigureCrudService', true],
            'App\\Controller\\Admin\\TaskCrudController::configureAssets' => ['privates', '.service_locator.49XXFvZ.App\\Controller\\Admin\\TaskCrudController::configureAssets()', 'getTaskCrudControllerconfigureAssetsService', true],
            'App\\Controller\\Admin\\TaskCrudController::configureFilters' => ['privates', '.service_locator.3Xb4Hur.App\\Controller\\Admin\\TaskCrudController::configureFilters()', 'getTaskCrudControllerconfigureFiltersService', true],
            'App\\Controller\\Admin\\TaskCrudController::index' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::index()', 'getTaskCrudControllerindexService', true],
            'App\\Controller\\Admin\\TaskCrudController::detail' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::detail()', 'getTaskCrudControllerdetailService', true],
            'App\\Controller\\Admin\\TaskCrudController::edit' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::edit()', 'getTaskCrudControllereditService', true],
            'App\\Controller\\Admin\\TaskCrudController::new' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::new()', 'getTaskCrudControllernewService', true],
            'App\\Controller\\Admin\\TaskCrudController::delete' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::delete()', 'getTaskCrudControllerdeleteService', true],
            'App\\Controller\\Admin\\TaskCrudController::batchDelete' => ['privates', '.service_locator.PNgi4kB.App\\Controller\\Admin\\TaskCrudController::batchDelete()', 'getTaskCrudControllerbatchDeleteService', true],
            'App\\Controller\\Admin\\TaskCrudController::autocomplete' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::autocomplete()', 'getTaskCrudControllerautocompleteService', true],
            'App\\Controller\\Admin\\TaskCrudController::createIndexQueryBuilder' => ['privates', '.service_locator.iydwXyk.App\\Controller\\Admin\\TaskCrudController::createIndexQueryBuilder()', 'getTaskCrudControllercreateIndexQueryBuilderService', true],
            'App\\Controller\\Admin\\TaskCrudController::renderFilters' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::renderFilters()', 'getTaskCrudControllerrenderFiltersService', true],
            'App\\Controller\\Admin\\TaskCrudController::updateEntity' => ['privates', '.service_locator.P.blNFL.App\\Controller\\Admin\\TaskCrudController::updateEntity()', 'getTaskCrudControllerupdateEntityService', true],
            'App\\Controller\\Admin\\TaskCrudController::persistEntity' => ['privates', '.service_locator.P.blNFL.App\\Controller\\Admin\\TaskCrudController::persistEntity()', 'getTaskCrudControllerpersistEntityService', true],
            'App\\Controller\\Admin\\TaskCrudController::deleteEntity' => ['privates', '.service_locator.P.blNFL.App\\Controller\\Admin\\TaskCrudController::deleteEntity()', 'getTaskCrudControllerdeleteEntityService', true],
            'App\\Controller\\Admin\\TaskCrudController::createEditForm' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createEditForm()', 'getTaskCrudControllercreateEditFormService', true],
            'App\\Controller\\Admin\\TaskCrudController::createEditFormBuilder' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createEditFormBuilder()', 'getTaskCrudControllercreateEditFormBuilderService', true],
            'App\\Controller\\Admin\\TaskCrudController::createNewForm' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createNewForm()', 'getTaskCrudControllercreateNewFormService', true],
            'App\\Controller\\Admin\\TaskCrudController::createNewFormBuilder' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createNewFormBuilder()', 'getTaskCrudControllercreateNewFormBuilderService', true],
            'App\\Controller\\Admin\\TaskCrudController::configureResponseParameters' => ['privates', '.service_locator.OgOMxLk.App\\Controller\\Admin\\TaskCrudController::configureResponseParameters()', 'getTaskCrudControllerconfigureResponseParametersService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator._1ARgjp.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\Admin\\TaskCrudController:configureActions' => ['privates', '.service_locator.LHPXyzR.App\\Controller\\Admin\\TaskCrudController::configureActions()', 'getTaskCrudControllerconfigureActionsService', true],
            'App\\Controller\\Admin\\TaskCrudController:configureCrud' => ['privates', '.service_locator.GLGWHcU.App\\Controller\\Admin\\TaskCrudController::configureCrud()', 'getTaskCrudControllerconfigureCrudService', true],
            'App\\Controller\\Admin\\TaskCrudController:configureAssets' => ['privates', '.service_locator.49XXFvZ.App\\Controller\\Admin\\TaskCrudController::configureAssets()', 'getTaskCrudControllerconfigureAssetsService', true],
            'App\\Controller\\Admin\\TaskCrudController:configureFilters' => ['privates', '.service_locator.3Xb4Hur.App\\Controller\\Admin\\TaskCrudController::configureFilters()', 'getTaskCrudControllerconfigureFiltersService', true],
            'App\\Controller\\Admin\\TaskCrudController:index' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::index()', 'getTaskCrudControllerindexService', true],
            'App\\Controller\\Admin\\TaskCrudController:detail' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::detail()', 'getTaskCrudControllerdetailService', true],
            'App\\Controller\\Admin\\TaskCrudController:edit' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::edit()', 'getTaskCrudControllereditService', true],
            'App\\Controller\\Admin\\TaskCrudController:new' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::new()', 'getTaskCrudControllernewService', true],
            'App\\Controller\\Admin\\TaskCrudController:delete' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::delete()', 'getTaskCrudControllerdeleteService', true],
            'App\\Controller\\Admin\\TaskCrudController:batchDelete' => ['privates', '.service_locator.PNgi4kB.App\\Controller\\Admin\\TaskCrudController::batchDelete()', 'getTaskCrudControllerbatchDeleteService', true],
            'App\\Controller\\Admin\\TaskCrudController:autocomplete' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::autocomplete()', 'getTaskCrudControllerautocompleteService', true],
            'App\\Controller\\Admin\\TaskCrudController:createIndexQueryBuilder' => ['privates', '.service_locator.iydwXyk.App\\Controller\\Admin\\TaskCrudController::createIndexQueryBuilder()', 'getTaskCrudControllercreateIndexQueryBuilderService', true],
            'App\\Controller\\Admin\\TaskCrudController:renderFilters' => ['privates', '.service_locator.HOzo2Xr.App\\Controller\\Admin\\TaskCrudController::renderFilters()', 'getTaskCrudControllerrenderFiltersService', true],
            'App\\Controller\\Admin\\TaskCrudController:updateEntity' => ['privates', '.service_locator.P.blNFL.App\\Controller\\Admin\\TaskCrudController::updateEntity()', 'getTaskCrudControllerupdateEntityService', true],
            'App\\Controller\\Admin\\TaskCrudController:persistEntity' => ['privates', '.service_locator.P.blNFL.App\\Controller\\Admin\\TaskCrudController::persistEntity()', 'getTaskCrudControllerpersistEntityService', true],
            'App\\Controller\\Admin\\TaskCrudController:deleteEntity' => ['privates', '.service_locator.P.blNFL.App\\Controller\\Admin\\TaskCrudController::deleteEntity()', 'getTaskCrudControllerdeleteEntityService', true],
            'App\\Controller\\Admin\\TaskCrudController:createEditForm' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createEditForm()', 'getTaskCrudControllercreateEditFormService', true],
            'App\\Controller\\Admin\\TaskCrudController:createEditFormBuilder' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createEditFormBuilder()', 'getTaskCrudControllercreateEditFormBuilderService', true],
            'App\\Controller\\Admin\\TaskCrudController:createNewForm' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createNewForm()', 'getTaskCrudControllercreateNewFormService', true],
            'App\\Controller\\Admin\\TaskCrudController:createNewFormBuilder' => ['privates', '.service_locator.o3gmRre.App\\Controller\\Admin\\TaskCrudController::createNewFormBuilder()', 'getTaskCrudControllercreateNewFormBuilderService', true],
            'App\\Controller\\Admin\\TaskCrudController:configureResponseParameters' => ['privates', '.service_locator.OgOMxLk.App\\Controller\\Admin\\TaskCrudController::configureResponseParameters()', 'getTaskCrudControllerconfigureResponseParametersService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\Admin\\TaskCrudController::configureActions' => '?',
            'App\\Controller\\Admin\\TaskCrudController::configureCrud' => '?',
            'App\\Controller\\Admin\\TaskCrudController::configureAssets' => '?',
            'App\\Controller\\Admin\\TaskCrudController::configureFilters' => '?',
            'App\\Controller\\Admin\\TaskCrudController::index' => '?',
            'App\\Controller\\Admin\\TaskCrudController::detail' => '?',
            'App\\Controller\\Admin\\TaskCrudController::edit' => '?',
            'App\\Controller\\Admin\\TaskCrudController::new' => '?',
            'App\\Controller\\Admin\\TaskCrudController::delete' => '?',
            'App\\Controller\\Admin\\TaskCrudController::batchDelete' => '?',
            'App\\Controller\\Admin\\TaskCrudController::autocomplete' => '?',
            'App\\Controller\\Admin\\TaskCrudController::createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\TaskCrudController::renderFilters' => '?',
            'App\\Controller\\Admin\\TaskCrudController::updateEntity' => '?',
            'App\\Controller\\Admin\\TaskCrudController::persistEntity' => '?',
            'App\\Controller\\Admin\\TaskCrudController::deleteEntity' => '?',
            'App\\Controller\\Admin\\TaskCrudController::createEditForm' => '?',
            'App\\Controller\\Admin\\TaskCrudController::createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\TaskCrudController::createNewForm' => '?',
            'App\\Controller\\Admin\\TaskCrudController::createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\TaskCrudController::configureResponseParameters' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\Admin\\TaskCrudController:configureActions' => '?',
            'App\\Controller\\Admin\\TaskCrudController:configureCrud' => '?',
            'App\\Controller\\Admin\\TaskCrudController:configureAssets' => '?',
            'App\\Controller\\Admin\\TaskCrudController:configureFilters' => '?',
            'App\\Controller\\Admin\\TaskCrudController:index' => '?',
            'App\\Controller\\Admin\\TaskCrudController:detail' => '?',
            'App\\Controller\\Admin\\TaskCrudController:edit' => '?',
            'App\\Controller\\Admin\\TaskCrudController:new' => '?',
            'App\\Controller\\Admin\\TaskCrudController:delete' => '?',
            'App\\Controller\\Admin\\TaskCrudController:batchDelete' => '?',
            'App\\Controller\\Admin\\TaskCrudController:autocomplete' => '?',
            'App\\Controller\\Admin\\TaskCrudController:createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\TaskCrudController:renderFilters' => '?',
            'App\\Controller\\Admin\\TaskCrudController:updateEntity' => '?',
            'App\\Controller\\Admin\\TaskCrudController:persistEntity' => '?',
            'App\\Controller\\Admin\\TaskCrudController:deleteEntity' => '?',
            'App\\Controller\\Admin\\TaskCrudController:createEditForm' => '?',
            'App\\Controller\\Admin\\TaskCrudController:createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\TaskCrudController:createNewForm' => '?',
            'App\\Controller\\Admin\\TaskCrudController:createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\TaskCrudController:configureResponseParameters' => '?',
        ]);
    }
}
