<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVoTJ3Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVoTJ3Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVoTJ3Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVoTJ3Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXVoTJ3Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'XVoTJ3Y',
    'container.build_id' => 'e165514f',
    'container.build_time' => 1731422202,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVoTJ3Y');
