<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTzI0jOd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTzI0jOd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTzI0jOd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTzI0jOd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTzI0jOd\App_KernelDevDebugContainer([
    'container.build_hash' => 'TzI0jOd',
    'container.build_id' => '2cd7a967',
    'container.build_time' => 1731358699,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTzI0jOd');
