<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_task_index' => [[], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::index'], [], [['text', '/admin/task/']], [], [], []],
    'admin_task_new' => [[], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::new'], [], [['text', '/admin/task/new']], [], [], []],
    'admin_task_batch_delete' => [[], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::batchDelete'], [], [['text', '/admin/task/batchDelete']], [], [], []],
    'admin_task_autocomplete' => [[], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::autocomplete'], [], [['text', '/admin/task/autocomplete']], [], [], []],
    'admin_task_render_filters' => [[], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::renderFilters'], [], [['text', '/admin/task/renderFilters']], [], [], []],
    'admin_task_edit' => [['entityId'], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'entityId', true], ['text', '/admin/task']], [], [], []],
    'admin_task_delete' => [['entityId'], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'entityId', true], ['text', '/admin/task']], [], [], []],
    'admin_task_detail' => [['entityId'], ['_controller' => 'App\\Controller\\Admin\\TaskCrudController::detail'], [], [['variable', '/', '[^/]++', 'entityId', true], ['text', '/admin/task']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\Admin\DashboardController::index' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
];
