name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
        contents: read
        packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Convert repository name to lowercase
      id: vars
      run: |
        REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    # Connectez-vous à GHCR avec le GITHUB_TOKEN
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Construisez l'image Docker
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_NAME }}/fastline1:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ env.REPO_NAME }}/fastline1:latest