name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main # Déclenche l'action sur un push vers la branche "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Vérifiez le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Connectez-vous à GHCR avec le GITHUB_TOKEN
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Construisez l'image Docker
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/fastline:latest .

    # Publiez l'image Docker sur GHCR
    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/fastline:latest
